M48
; DRILL file {KiCad 7.0.5} date Wed Mar  6 10:34:55 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-06T10:34:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X-0.1417Y-0.172
X0.1415Y-0.1707
T2
X-0.655Y0.27
X-0.335Y-0.33
X0.335Y-0.33
X0.655Y0.27
T0
M30
